on:
  workflow_dispatch:
  workflow_run:
    workflows: ["pingW"]
    repo: ozzShpigel/actions-remote-dispatch-a
    branches: [main]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "main 1th"