name: Manually triggered workflow
on: workflow_dispatch

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: www 
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: test
          repo: ozzShpigel/actions-remote-dispatch-a
          token: ${{ secrets.ACCESS_TOKEN }}